apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvclaim
  namespace: jenkins
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
