apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master-deployment
  namespace: jenkins
  labels:
    app: jenkins-master
    group: jenkins

spec:
  replicas: 1

  selector:
      matchLabels:
        app: jenkins-master
        version: latest
        group: jenkins

  template:
    metadata:
      labels:
        app: jenkins-master
        version: latest
        group: jenkins

    spec:
      serviceAccountName: jenkins-admin # The name of the service account is jenkins-admin
      securityContext:
          fsGroup: 1000
          runAsUser: 1000

      containers:
        - name: jenkins-master
          image: techielins/jenkins-master:v1
          imagePullPolicy: IfNotPresent

          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false

          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000

          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: jenkins-persistent-storage
              mountPath: /var/jenkins_home

      volumes:
        - name: jenkins-persistent-storage
          persistentVolumeClaim:
            claimName: jenkins-pvclaim
            readOnly: false           
