AWSTemplateFormatVersion: 2010-09-09
Description: VPC

Resources:
  # First, a VPC:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Provisioned By
        Value:  mylins cloudformation

# Create Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Provisioned By
          Value: mylins cloudformation
         
# Attach Internet Gateway to VPC
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

# Create Public Subnet 10.0.1.0/24
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Provisioned By
        Value:  mylins cloudformation

# Create Private Subnet 10.0.3.0/24
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: false

# Create Public Route Table for the VPC
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Provisioned By
        Value:  mylins cloudformation

# Create default route for internet access via Internet Gateway
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

# Create Public Route Table association for Public subnet
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

# Create Security Group for allow ping
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable ping
      SecurityGroupEgress:
        - FromPort: '-1'
          ToPort: '-1'
          IpProtocol:  "icmp"
          CidrIp: "0.0.0.0/0"
      SecurityGroupIngress:
        - IpProtocol: "icmp"
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: "0.0.0.0/0"
      VpcId: !Ref VPC       

# Create EC2 instance in Public Subnet
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02d8b16971a4906a0
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds: 
        - !Ref SecurityGroup
      Tags:
      - Key: Provisioned By
        Value:  mylins cloudformation

  